# -*- coding: utf-8 -*-
"""speech rocognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cas1aQJ9Db89qbatTjvavYETPqCzP4s5
"""

pip install SpeechRecognition



pip install pyttsx3

!apt-get update
!apt-get install espeak

import speech_recognition as sr
import pyttsx3

# Initialize recognizer and text-to-speech engine
recognizer = sr.Recognizer()
engine = pyttsx3.init()

# Load audio file
audio_path = "/content/Audio from ~PrIyA.wav"  # replace with your actual file
with sr.AudioFile(audio_path) as source:
    print("Listening to audio file...")
    audio_data = recognizer.record(source)

try:
    # Recognize speech using Google's neural net
    text = recognizer.recognize_google(audio_data)
    print("Recognized Text:", text)

    # Speak out the recognized text
    engine.say("You said: " + text)
    engine.runAndWait()

except sr.UnknownValueError:
    print("Sorry, could not understand the audio.")
    engine.say("Sorry, I could not understand.")
    engine.runAndWait()

except sr.RequestError as e:
    print(f"Request failed: {e}")
    engine.say("There was an error with the speech service.")
    engine.runAndWait()